class MultipleResultsError(Exception):
    """複数の結果が返ってきた場合の例外"""
    pass